### ISSUE TITLE
Segfault in CQRRP_Blocked compiled with ICPX

### ISSUE THREAD

**Issue by rileyjmurray** [BallisticLA/RandLAPACK#91]
I find myself needing to use the Intel compiler toolchain. Everything seems to build fine (although I get a lot of warnings in RandBLAS for dynamically-sized arrays). All tests pass except for TestCQRRP.CQRRP_blocked_gemqrt.

I've saved configuration files and I can post them here later. For now, I'll just note the error from ctest with the address sanitizer turned on.

```
[rjmurr@sn1 RandLAPACK-build]$ ctest -R TestCQRRP --output-on-failure --rerun-failed
Test project /home/rjmurr/laps/RandLAPACK-build
    Start 292: TestCQRRP.CQRRP_blocked_gemqrt
1/1 Test #292: TestCQRRP.CQRRP_blocked_gemqrt ...***Failed    4.26 sec
Running main() from /tmp/rjmurr/spack-stage/spack-stage-googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/spack-src/googletest/src/gtest_main.cc
Note: Google Test filter = TestCQRRP.CQRRP_blocked_gemqrt
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestCQRRP
[ RUN      ] TestCQRRP.CQRRP_blocked_gemqrt
=================================================================
==1668130==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x50200016df10 in thread T0
    #0 0x526a91 in operator delete(void*) (/home/rjmurr/laps/RandLAPACK-build/bin/RandLAPACK_tests+0x526a91)
    #1 0x7f47cfa73c55 in lapack::gemqrt(blas::Side, blas::Op, long, long, long, long, double const*, long, double const*, long, double*, long) (/home/rjmurr/laps/lapp-install/lib64/liblapackpp.so.1+0x45c55)
    #2 0x6b8808 in RandLAPACK::CQRRP_blocked<double, r123::Philox4x32_R<10u>>::call(long, long, double*, long, double, double*, long*, RandBLAS::RNGState<r123::Philox4x32_R<10u>>&) /home/rjmurr/laps/RandLAPACK/RandLAPACK/../RandLAPACK/drivers/rl_cqrrp.hh:478:13
    #3 0x6b3284 in void TestCQRRP::test_CQRRP_general<double, r123::Philox4x32_R<10u>, RandLAPACK::CQRRP_blocked<double, r123::Philox4x32_R<10u>>>(double, double, TestCQRRP::CQRRPTestData<double>&, RandLAPACK::CQRRP_blocked<double, r123::Philox4x32_R<10u>>&, RandBLAS::RNGState<r123::Philox4x32_R<10u>>&) /home/rjmurr/laps/RandLAPACK/test/drivers/test_cqrrp.cc:122:15
    #4 0x699215 in TestCQRRP_CQRRP_blocked_gemqrt_Test::TestBody() /home/rjmurr/laps/RandLAPACK/test/drivers/test_cqrrp.cc:262:5
    #5 0x7f47a2e727fc in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x5f7fc)
    #6 0x7f47a2e56735 in testing::Test::Run() (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x43735)
    #7 0x7f47a2e56904 in testing::TestInfo::Run() (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x43904)
    #8 0x7f47a2e56bcc in testing::TestSuite::Run() (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x43bcc)
    #9 0x7f47a2e6ae28 in testing::internal::UnitTestImpl::RunAllTests() (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x57e28)
    #10 0x7f47a2e4c723 in testing::UnitTest::Run() (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x39723)
    #11 0x7f47a308dbaa in main (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest_main.so.1.14.0+0xbaa)
    #12 0x7f47a1e93d84 in __libc_start_main (/lib64/libc.so.6+0x3ad84) (BuildId: 31f2a86084da882dfe4ecc1fe2a9eca8ce9416fd)
    #13 0x43e1fd in _start (/home/rjmurr/laps/RandLAPACK-build/bin/RandLAPACK_tests+0x43e1fd)

0x50200016df10 is located 16 bytes after 16-byte region [0x50200016def0,0x50200016df00)
allocated by thread T0 here:
    #0 0x526211 in operator new(unsigned long) (/home/rjmurr/laps/RandLAPACK-build/bin/RandLAPACK_tests+0x526211)
    #1 0x6bd465 in testing::internal::TestFactoryImpl<TestCQRRP_CQRRP_blocked_gemqrt_Test>::CreateTest() /home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/include/gtest/internal/gtest-internal.h:457:40
    #2 0x7f47a2e729dc in testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) (/home/rjmurr/spack/opt/spack/linux-rhel8-zen3/gcc-12.2.0/googletest-1.14.0-ous4kpjfhnzviyjapd4zbrpodbzrpby7/lib64/libgtest.so.1.14.0+0x5f9dc)

SUMMARY: AddressSanitizer: bad-free (/home/rjmurr/laps/RandLAPACK-build/bin/RandLAPACK_tests+0x526a91) in operator delete(void*)
==1668130==ABORTING


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.26 sec

The following tests FAILED:
        292 - TestCQRRP.CQRRP_blocked_gemqrt (Failed)
Errors while running CTest
```

**Comment by mmelnich** [comment]
## Status: not reproduced, but on a materially different machine, so this does not close the issue

First, a naming note so this thread is readable: `CQRRP_blocked` no longer exists. It was renamed to `BQRRP`, and the test named here, `TestCQRRP.CQRRP_blocked_gemqrt`, is now `TestBQRRP.BQRRP_gemqrt` (`test/drivers/test_bqrrp.cc:242`). The `gemqrt` call sites the traceback passes through are `RandLAPACK/drivers/rl_bqrrp.hh:537` and `:543`, so the code path in question is still present and still reachable.

## What was run

Built current `main` with the Intel toolchain and AddressSanitizer, then ran the QRCP suites:

- Compiler: Intel oneAPI DPC++/C++ 2026.0.0 (2026.0.0.20260331)
- Filter: `TestBQRRP|TestCQRRPT|TestHQRRP`, 20 tests
- Result: **20/20 passed, no sanitizer reports**

`TestBQRRP.BQRRP_gemqrt` passes on its own as well, and specifically exercises the path where the bad free occurred (`apply_trans_q == ApplyTransQ::gemqrt` with `qr_tall` in `{geqrt, cholqr}`).

## Why that is not enough to close this

The original report came from a `linux-rhel8-zen3` environment, so **AMD Zen 3**. This run was on an **Intel** host, with a 2026 Intel compiler rather than the 2024-era one in the original traceback, and against our own LAPACK++ build.

Those differences matter more than usual here, because the invalid free was raised *inside* `lapack::gemqrt` rather than in RandLAPACK code:

```
#1 ... in lapack::gemqrt(...) (liblapackpp.so.1+0x45c55)
#2 ... in RandLAPACK::CQRRP_blocked<...>::call(...) rl_cqrrp.hh:478
```

That points at LAPACK++ workspace handling, which is sensitive to how LAPACK++ itself was configured and which backend it resolved to. A clean run under a different compiler version, different backend build and different microarchitecture is therefore weak evidence that the defect is gone, as opposed to not triggered.

Proposal: keep this open until the same build is run on an AMD host. If it stays clean there, the honest conclusion is that the intervening rewrite fixed it, and this can close with both transcripts attached. If it reproduces, it belongs upstream in LAPACK++ with a minimal reproducer rather than here.

## Incidental blocker found while setting this up

`-DSANITIZE_ADDRESS=ON` cannot be used with the Intel compiler today. RandBLAS gates the sanitizer flags on `CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang"` and otherwise hard-errors (`RandBLAS/RandBLAS/CMakeLists.txt:77-86`). `icpx` reports `IntelLLVM`, so it takes the `FATAL_ERROR` branch even though it accepts Clang's `-fsanitize=address` verbatim. I worked around it by passing the flags through `CMAKE_CXX_FLAGS` manually.

Worth extending that match to cover `IntelLLVM`, otherwise anyone retesting this issue hits the same wall first. Happy to file that separately against RandBLAS if it is wanted.
